name: "Contribution Closed - Auto Triage"

on:
  pull_request:
    branches: [main]
    types: [closed, converted_to_draft]
  issues:
    types: [closed]

permissions:
  pull-requests: write
  issues: write

jobs:
  Triage:
    runs-on: ubuntu-latest
    name: Contribution by ${{github.actor}} - Auto Triage
    steps:
        - name: âš™ï¸ Checkout Repo
          uses: actions/checkout@v4
          with:
            path: configRepo
            
        - name: ğŸ“‹ End Triage
          uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const endTriage = require('./configRepo/.github/scripts/auto-triage/end.js');
              await endTriage({ github, context, core })

        - name: ğŸ¥³ Success
          run: echo Triage has completed successfully!
           