name: "New Contribution - Auto Triage"

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, ready_for_review]
  issues:
    types: [opened, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  Triage:
    runs-on: ubuntu-latest
    name: Contribution by ${{github.actor}} - Auto Triage
    steps:
        - name: âš™ï¸ Checkout Repo
          uses: actions/checkout@v4
          with:
            path: configRepo
            
        - name: ğŸ“‹ Start Triage
          uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const startTriage = require('./configRepo/.github/scripts/auto-triage/start.js');
              await startTriage({ github, context, core })

        - name: ğŸ¥³ Success
          run: echo Triage has completed successfully!
           